server:
  port: 8080
  maxHttpHeaderSize: 4194304
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 2097162
#===datasource start===
spring:
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: dts-demo
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 3MB
    #mongodb配置



  #mongodb配置
  data:
    mongodb:
      database: dts
      host: localhost
      port: 27017
      authentication-database: admin
      #      username:
      #      password:
      repositories:
        type: auto


  thymeleaf:
    prefix: classpath:/pages/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: hhz
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启的目录，检索目录(resources/static、resources/templates)
      additional-paths: src/main/java


